apiVersion: apps/v1
kind: Deployment
metadata:
  name: trex-deployment
  labels:
    app: trex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trex
  template:
    metadata:
      labels:
        app: trex
    spec:
      containers:
      - name: trex
        image: trexcisco/trex:2.36
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "sleep 300000000" ]
        ports:
        - containerPort: 4500
